services:
  mongodb:
    image: mongo:6.0
    container_name: game-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    container_name: game-redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
  mongo-data:
    driver: local
