server:
  host: "0.0.0.0"
  port: "80"

redis:
  host: "redis"
  port: "6379"

static:
  game: "./internal/html/game/dist"
  home: "./internal/html/home/dist"

resources:
  - name: "server_0"
    endpoint: "/server_0/socket.io/"
    desination_url: "http://game-server:8080/"
  - name: "server_1"
    endpoint: "/server_1/socket.io/"
    desination_url: "http://localhost:8081/"
  - name: "api"
    endpoint: "/api/"
    desination_url: "http://game-api:5000/"
