apiVersion: v1
kind: Service
metadata:
  name: game-server
  labels:
    app: game-server
  namespace: rts-game
spec:
  selector:
    app: game-server
  ports:
    - port: 8080
      targetPort: 8080
